insights <- c('page_stories', 'page_storytellers', 'page_stories_by_story_type', 'page_storytellers_by_story_type', 'page_storytellers_by_age_gender', 'page_storytellers_by_city', 'page_storytellers_by_country', 'page_storytellers_by_locale', 'post_stories', 'post_storytellers', 'post_stories_by_action_type', 'post_storytellers_by_action_type',
              'page_impressions', 'page_impressions_unique', 'page_impressions_paid', 'page_impressions_paid_unique', 'page_impressions_organic', 'page_impressions_organic_unique', 'page_impressions_viral', 'page_impressions_viral_unique', 'page_impressions_by_story_type', 'page_impressions_by_story_type_unique', 'page_impressions_by_city_unique', 'page_impressions_by_country_unique', 'page_impressions_by_locale_unique', 'page_impressions_by_age_gender_unique', 'page_impressions_frequency_distribution', 'page_impressions_viral_frequency_distribution', 'page_impressions_by_paid_non_paid', 'page_impressions_by_paid_non_paid_unique',
              'page_engaged_users', 'page_consumptions', 'page_consumptions_unique', 'page_consumptions_by_consumption_type', 'page_consumptions_by_consumption_type_unique', 'page_places_checkin_total', 'page_places_checkin_total_unique', 'page_places_checkin_mobile', 'page_places_checkin_mobile_unique', 'page_places_checkins_by_age_gender', 'page_places_checkins_by_locale', 'page_places_checkins_by_country', 'page_negative_feedback', 'page_negative_feedback_unique', 'page_negative_feedback_by_type', 'page_negative_feedback_by_type_unique', 'page_positive_feedback_by_type', 'page_positive_feedback_by_type_unique', 'page_fans_online', 'page_fans_online_per_day',
              'page_fans', 'page_fans_locale', 'page_fans_city', 'page_fans_country', 'page_fans_gender_age', 'page_fan_adds', 'page_fan_adds_unique', 'page_fans_by_like_source', 'page_fans_by_like_source_unique', 'page_fan_removes', 'page_fan_removes_unique', 'page_fans_by_unlike_source_unique',
              'page_tab_views_login_top_unique', 'page_tab_views_login_top', 'page_tab_views_logout_top',
              'page_views', 'page_views_unique', 'page_views_login', 'page_views_login_unique', 'page_views_logout', 'page_views_external_referrals',
              'page_posts_impressions', 'page_posts_impressions_unique', 'page_posts_impressions_paid', 'page_posts_impressions_paid_unique', 'page_posts_impressions_organic', 'page_posts_impressions_organic_unique', 'page_posts_impressions_viral', 'page_posts_impressions_viral_unique', 'page_posts_impressions_frequency_distribution', 'page_posts_impressions_by_paid_non_paid', 'page_posts_impressions_by_paid_non_paid_unique',
              'post_impressions', 'post_impressions_unique', 'post_impressions_paid', 'post_impressions_paid_unique', 'post_impressions_fan', 'post_impressions_fan_unique', 'post_impressions_fan_paid', 'post_impressions_fan_paid_unique', 'post_impressions_organic', 'post_impressions_organic_unique', 'post_impressions_viral', 'post_impressions_viral_unique', 'post_impressions_by_story_type', 'post_impressions_by_story_type_unique', 'post_impressions_by_paid_non_paid', 'post_impressions_by_paid_non_paid_unique',
              'post_consumptions', 'post_consumptions_unique', 'post_consumptions_by_type', 'post_consumptions_by_type_unique', 'post_engaged_users', 'post_negative_feedback', 'post_negative_feedback_unique', 'post_negative_feedback_by_type', 'post_negative_feedback_by_type_unique',
              'post_video_avg_time_watched', 'post_video_complete_views_organic', 'post_video_complete_views_organic_unique', 'post_video_complete_views_paid', 'post_video_complete_views_paid_unique', 'post_video_length', 'post_video_retention_graph', 'post_video_views_organic', 'post_video_views_organic_unique', 'post_video_views_paid', 'post_video_views_paid_unique')

#Facebook doesn't seem to like this
ptat_insights <- c('page_stories', 'page_storytellers', 'page_stories_by_story_type', 'page_storytellers_by_story_type', 'page_storytellers_by_age_gender', 'page_storytellers_by_city', 'page_storytellers_by_country', 'page_storytellers_by_locale', 'post_stories', 'post_storytellers', 'post_stories_by_action_type', 'post_storytellers_by_action_type')

page_impressions_insights <- c('page_impressions', 'page_impressions_unique', 'page_impressions_paid', 'page_impressions_paid_unique', 'page_impressions_organic', 'page_impressions_organic_unique', 'page_impressions_viral', 'page_impressions_viral_unique', 'page_impressions_by_story_type', 'page_impressions_by_story_type_unique', 'page_impressions_by_city_unique', 'page_impressions_by_country_unique', 'page_impressions_by_locale_unique', 'page_impressions_by_age_gender_unique', 'page_impressions_frequency_distribution', 'page_impressions_viral_frequency_distribution', 'page_impressions_by_paid_non_paid', 'page_impressions_by_paid_non_paid_unique')

page_engagement_insights <- c('page_engaged_users', 'page_consumptions', 'page_consumptions_unique', 'page_consumptions_by_consumption_type', 'page_consumptions_by_consumption_type_unique', 'page_places_checkin_total', 'page_places_checkin_total_unique', 'page_places_checkin_mobile', 'page_places_checkin_mobile_unique', 'page_places_checkins_by_age_gender', 'page_places_checkins_by_locale', 'page_places_checkins_by_country', 'page_negative_feedback', 'page_negative_feedback_unique', 'page_negative_feedback_by_type', 'page_negative_feedback_by_type_unique', 'page_positive_feedback_by_type', 'page_positive_feedback_by_type_unique', 'page_fans_online', 'page_fans_online_per_day')

#Facebook doesn't seem to like this
page_user_insights <- c('page_fans', 'page_fans_locale', 'page_fans_city', 'page_fans_country', 'page_fans_gender_age', 'page_fan_adds', 'page_fan_adds_unique', 'page_fans_by_like_source', 'page_fans_by_like_source_unique', 'page_fan_removes', 'page_fan_removes_unique', 'page_fans_by_unlike_source_unique')

page_content_insights <- c('page_tab_views_login_top_unique', 'page_tab_views_login_top', 'page_tab_views_logout_top')

page_views_insights <- c('page_views', 'page_views_unique', 'page_views_login', 'page_views_login_unique', 'page_views_logout', 'page_views_external_referrals')

page_posts_insights <- c('page_posts_impressions', 'page_posts_impressions_unique', 'page_posts_impressions_paid', 'page_posts_impressions_paid_unique', 'page_posts_impressions_organic', 'page_posts_impressions_organic_unique', 'page_posts_impressions_viral', 'page_posts_impressions_viral_unique', 'page_posts_impressions_frequency_distribution', 'page_posts_impressions_by_paid_non_paid', 'page_posts_impressions_by_paid_non_paid_unique')

page_post_impressions_insights <- c('post_impressions', 'post_impressions_unique', 'post_impressions_paid', 'post_impressions_paid_unique', 'post_impressions_fan', 'post_impressions_fan_unique', 'post_impressions_fan_paid', 'post_impressions_fan_paid_unique', 'post_impressions_organic', 'post_impressions_organic_unique', 'post_impressions_viral', 'post_impressions_viral_unique', 'post_impressions_by_story_type', 'post_impressions_by_story_type_unique', 'post_impressions_by_paid_non_paid', 'post_impressions_by_paid_non_paid_unique')

page_post_engagement_insights <- c('post_consumptions', 'post_consumptions_unique', 'post_consumptions_by_type', 'post_consumptions_by_type_unique', 'post_engaged_users', 'post_negative_feedback', 'post_negative_feedback_unique', 'post_negative_feedback_by_type', 'post_negative_feedback_by_type_unique')

page_video_posts_insights <- c('post_video_avg_time_watched', 'post_video_complete_views_organic', 'post_video_complete_views_organic_unique', 'post_video_complete_views_paid', 'post_video_complete_views_paid_unique', 'post_video_length', 'post_video_retention_graph', 'post_video_views_organic', 'post_video_views_organic_unique', 'post_video_views_paid', 'post_video_views_paid_unique')
